import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "welcome to modern js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         {/* <header className="bg-blue-600 text-white p-4 text-center font-bold">
          My App Header
        </header> */}

        {/* Global Navbar
        <nav className="bg-blue-200 p-2 flex justify-center gap-4">
          <a href="/" className="hover:text-blue-800">Home</a>
          <a href="/hello" className="hover:text-blue-800">About</a>
        </nav> */}
        <main className="p-4">{children}</main>
         {/* <footer className="bg-gray-300 text-center p-4">
          My App Footer © 2025
        </footer> */}
      </body>
    </html>
  );
}
